server:
  port: 9000
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.130:3306/my_12306
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 192.168.88.130 # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: wuyanzu666 # Redis服务器连接密码（默认为空）
      lettuce:
        pool:
          enabled: true
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: 192.168.88.130:8848
        cluster-name: GD

    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    # sentinel
    sentinel:
      transport:
        dashboard: 192.168.88.130:8080
      web-context-unify: false
      datasource:
        flow:
          nacos:
            server-addr: 192.168.88.130:8080
            data-id: user-service
            group-id: SENTINEL_GROUP
            rule-type: flow

    openfeign:
      httpclient:
        enabled: true
# feign
feign:
  sentinel:
    enabled: true

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn