server:
  port: 9000
spring:
  application:
    name: index12306-gateway-service
  profiles:
    # active: aggregation
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.130:8848
