server:
  port: 10000
spring:
  application:
    name: index12306-gateway-service
  profiles:
    active: '@environment@'
  cloud:
    nacos:
      discovery:
        server-addr: 47.120.9.134:8848

  data:
    redis:
      host: 192.168.88.130 # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: wuyanzu666 # Redis服务器连接密码（默认为空）
      lettuce:
        pool:
          enabled: true
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
    loadbalancer:
      nacos:
        enabled: true