# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'

# 项目配置
index-12306:
  # 不检查 same-token，在开发环境下允许直接访问子服务进行接口测试
  check-same-token: false
  # 是否将日志信息添加进数据库
  insert-logs: false

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    # 打印 sql 日志
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl